### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Chanhao** [xiaomaoJT/clash#1]
![5421683515943_ pic](https://user-images.githubusercontent.com/8262705/236726308-4beb4aca-5d08-463d-93b3-b38dcb1995ba.jpg)

**Comment by xiaomaoJT** [comment]
请于第四步，将openai策略删除，此远程规则有误，后续将做改进
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/49260609/236728768-dc998dcb-db6b-44c1-9b45-a9e5c2314d96.png">

**Comment by xiaomaoJT** [comment]
已修复

**Comment by Chanhao** [comment]
大佬辛苦
